---
title: Big data and cloud computing
author: Kabita Paul
date: '2019-04-20'
slug: big-data-and-cloud-computing
categories:
  - big data
tags:
  - R Markdown
---
The power of computing is being used today in such a great way that was never done before. Big data, analytic tools and power of internet have pushed the boundaries of conventional way of business. Starting from the online retail store, power of computing and informatics has established its way in all the sectors like agriculture, healthcare, social media and many more. The advancement in the field of analytics provides business a greater advantage to serve customer in a better way than before. Few start-up companies came to market with innovative business ideas like predicting farmer’s crop insurance based on weather forecast simulations combining with agricultural data. If this system had to be designed few decades back, huge Infrastructure would have been required to store the enormous amount of data. The cloud computing technology came into picture to provide infrastructure to companies with advantage of scalable, instant and cost effective services. Companies who require servers for processing huge amount of data can use cloud services instead of using physical servers. The subscription cost for the cloud based services is significantly lower than that would have been required to setup and maintain equivalent infrastructure on premises. Companies using the services of cloud can scale up their business as per requirement instantly and need to pay for the service as per their usage. Not only scalability and lower infrastructural cost, it also reduces the number of human resources, further lowering the expenditure of the company. Lower infrastructural and operational expenses reduce the cost of product or service, thereby helping businesses to satisfy more and more customers. With each passing day, more and more industries and businesses and leveraging Cloud services to get desired result.

Consumers, while buying products or services rely on ratings and reviews provided by other customers. The online review services that are available in existing market can be improved significantly with the use of Big-data and cloud services. Let us consider a situation where Mr X is willing to buy a laptop that is best fit for him and available at best price. Before buying it, he checks several laptops in different online stores and reads reviews of those. Any customer has to spend long time in checking reviews to find out which one to buy. Moreover, the liking or disliking for products varies person to person. The reviews which are written by persons of similar thinking, habits and preferences as Mr X are more useful for him. A centralised review app can be designed which can tell a customer about products that would be best suited for him, As an example, when a customer searches laptop, it shows a list of laptops based on reviews of customers with similar preference, and arranges them as most liked product on top.
To develop this ‘Online review app’, the system has to collect data from several sources like customer’s purchase history, social media, products descriptions from retail stores, rating and reviews and many more. After collecting the information, data need to be managed in Relational Database. The key attributes of a consumer need to be identified when it comes to customers’ habit, preference and usage of a product in order to create the structure of Database. In this case, a huge computing power is needed for data managing, data mining, and data processing.  The cloud services will provide a platform to build the infrastructure. When customers use this online review service, they can get to know about the best suited product for him from a single system which saves valuable time of consumers. Moreover, the result will be more accurate as this will be designed keeping customers’ preferences in mind.
